# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: B3LkKUpcZVx4bpLXKXpiez%R

# Documentation: https://roots.io/trellis/docs/security/
vault_sudoer_passwords:
  admin: $6$rounds=100000$JUkj1d3hCa6uFp6R$3rZ8jImyCpTP40e4I5APx7SbBvDCM8fB6GP/IGOrsk/GEUTUhl1i/Q2JNOpj9ashLpkgaCxqMqbFKdZdmAh26/

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  edziza.com:
    env:
      db_password: 6fVCeFfMbC4dDCrDFqrp{jgP
      # Generate your keys here: https://api.wordpress.org/secret-key/1.1/salt/
      auth_key: ":zG@4+6-f-60ame_}jG*&_8^m+S)pQl*wL)i3_ NEPR,~p8@n ru}8I@s4-Fku20"
      secure_auth_key: "jQV3}@O6-,!h)X|*/uI-ZF$LgT`y9>UdnhvZAVs:D~Rqq=12ti/4C)Td+tAUGibm"
      logged_in_key: "b,Q-g;%#|_V{].=ft^:5sI;cP5t[3V;UhJ >#b<nj bvg!y?M^ai9vEx;}y,.:$0"
      nonce_key: "|)AU[*GH@/2[;.zByJ|AzX4nb5]u]pMbP32Fq&P|[@G7-=jcREZ-20S?u7]e@`gd"
      auth_salt: "ZzLN4jj{7tdVWf4 h1~^ZB|Jm5gXC@L}-|/Mpn9Y0HeRStAg2z,EG6s0+p7jV*LG"
      secure_auth_salt: "-!|Vha0A#=L18{?!r*~+p~)z.p1}:)QyC1U9QCJl``{,~cZ+6X+|(3&o.PUf1e7="
      logged_in_salt: "|s_WxeHiS_Hok?9C**ETH-uutx*>5VE1100 2`y$+?P|T$;Llp:0_kF}qks{,W<F"
      nonce_salt: "6|6$S)*<>)4|O64v,e$2C|nMCvM2|6EkJi<^|>!-F^@VJm2t&g3Iro6_Jk=gq<?|"
